# Generated by Django 5.1.2 on 2024-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
